### ISSUE TITLE
Recursive keyrings and defaults

### ISSUE THREAD

**Issue by DylanScottCarroll** [sizemore0125/skeletonkey#22]
Currently in skeletonkey, the special keywords `keyring` and `defaults` only apply to the main config and not any subconfigs that are brought into it via `defaults` or `keyring`s.

Take for example the following set of configs loading different versions of the same keyring:
`main.yaml`
``` yaml
defaults:
    - "path/to/test_datasets.yaml"
    #- "path/to/train_datasets.yaml"
```

Where both `train_datasets.yaml` and `test_datasets.yaml` contain keyrings for the same set of datasets, but one has only testing datasets and the other has training datasets. `train_dataset.yaml` might look something like this:

``` yaml
keyring:
    datasets:
        dataset1: "datasets/train/dataset1.yaml"
        dataset2: "datasets/train/dataset2.yaml"
```

There are likely also scenarios in which it would be useful to used the `defaults` keyword in a sub-config to override values at that level. This sort of behavior would require that `keyring` and `defaults` be searched for and correctly parsed recursively in all sub-configs as well as the top-level config.
