### ISSUE TITLE
Skeletonkey does not properly parse yaml lists

### ISSUE THREAD

**Issue by DylanScottCarroll** [sizemore0125/skeletonkey#44]
If there are configurations inside a list in a yaml file, skeletonkey will not recurse into that list when creating a config object out of it. Take the following yaml file as an example:
``` yaml
main:
  sub_dict:
    a: a_val
    b: b_val

  sub_list:
    - a: a_val
      b: b_val
    - c: c_val
      d: d_val
```

When we unlock this file currently, we get  the following:
```
main:
  sub_dict:
    a: a_val
    b: b_val
  sub_list: [{'a': 'a_val', 'b': 'b_val'}, {'c': 'c_val', 'd': 'd_val'}]
```
The values inside `sub_list` are dictionaries rather than config objects . The presence of a list in the yaml file breaks the expectation that skeletonkey won't format the config as a dictionary.

---

It may also be useful in some cases to specify a list of config objects.

Consider the following example
``` yaml
layers:
  - _target_: main.linear_layer
    inpiut_size: 10
    output_size: 100

  -  _target_: main.linear_layer
    inpiut_size: 100
    output_size: 1
```

Then. it would be possible to do one of the following in code:
``` python
@sk.unlock(config.yaml)
def main(config)
    layer_zero = config.layers[0]() # Instantiates layer zero only 
    # or
    layers = sk.instantiate(*config.layers) # Instantiate all of the layers
```
